/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import controladores.ControladorSepararQuirofano;
import enums.TipoCirugia;
import excepciones.AgendaException;
import excepciones.MantenimientoQuirofanoException;
import excepciones.MedicoNoEsCirujanoException;
import java.time.DateTimeException;
import java.time.LocalDate;
import java.time.LocalTime;
import java.time.ZoneId;
import java.time.format.DateTimeParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import modelos.Cirugia;
import modelos.Medico;
import modelos.Paciente;
import modelos.Quirofano;
import modelos.Separado;

/**
 *
 * @author LENOVO
 */
public class VentanaQuirofano extends javax.swing.JInternalFrame {
    private ControladorSepararQuirofano controlador;

    /**
     * Creates new form VentanaQuirofano
     */
    public VentanaQuirofano(Quirofano quirofano) {
        initComponents();
        this.controlador = new ControladorSepararQuirofano(quirofano);
        llenarComboBox();
    }
    
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipoCirugia = new javax.swing.JLabel();
        cbxTipoCirugia = new javax.swing.JComboBox<>();
        lblCedulamedico = new javax.swing.JLabel();
        txtCedula = new javax.swing.JTextField();
        lblCedulaPaciente = new javax.swing.JLabel();
        lblFechaCirugia = new javax.swing.JLabel();
        lblHoraCirugia = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        txtCedulaPaciente = new javax.swing.JTextField();
        txtMotivo = new javax.swing.JTextField();
        fechaCirugia = new com.toedter.calendar.JDateChooser();
        horaCirugia = new javax.swing.JFormattedTextField();
        btnReservar = new javax.swing.JButton();
        lblDuracion = new javax.swing.JLabel();
        spnduracionCirugia = new javax.swing.JSpinner();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ventana reserva quirofano");

        lblTipoCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblTipoCirugia.setText("Tipo cirugía");

        cbxTipoCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        cbxTipoCirugia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCedulamedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblCedulamedico.setText("Cédula médico");

        txtCedula.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        lblCedulaPaciente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblCedulaPaciente.setText("Cédula paciente");

        lblFechaCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFechaCirugia.setText("Fecha Cirugía");

        lblHoraCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblHoraCirugia.setText("Hora cirugía");

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblMotivo.setText("Motivo");

        txtCedulaPaciente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        fechaCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        try {
            horaCirugia.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        horaCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        btnReservar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnReservar.setText("Reservar");
        btnReservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReservarActionPerformed(evt);
            }
        });

        lblDuracion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblDuracion.setText("Duración cirugía");

        spnduracionCirugia.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblTipoCirugia)
                            .addComponent(spnduracionCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(366, 366, 366)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCedulaPaciente)
                            .addComponent(lblFechaCirugia)
                            .addComponent(lblHoraCirugia)
                            .addComponent(lblMotivo))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaCirugia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtCedulaPaciente)
                                .addComponent(txtMotivo)
                                .addComponent(fechaCirugia, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxTipoCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCedulamedico)
                            .addComponent(lblDuracion))
                        .addGap(406, 406, 406)
                        .addComponent(btnReservar))
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTipoCirugia, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCedulaPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblCedulaPaciente)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fechaCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFechaCirugia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(horaCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblHoraCirugia))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMotivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMotivo)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(cbxTipoCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lblDuracion)
                        .addGap(18, 18, 18)
                        .addComponent(spnduracionCirugia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(lblCedulamedico)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnReservar)))
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnReservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReservarActionPerformed
        // TODO add your handling code here:
        if(camposVacios()){
            JOptionPane.showMessageDialog(null, "Ingrese todos los datos");
            return;
        }
        
        String tipoCirugia = (String) cbxTipoCirugia.getSelectedItem();
        TipoCirugia tipo = TipoCirugia.valueOf(tipoCirugia.toUpperCase());
        
        String motivo = txtMotivo.getText();
        Date date = fechaCirugia.getDate();
        
        LocalDate fecha = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        int duracionCirugia = (int) spnduracionCirugia.getValue();
        
        try{
            String cedulaMedico = txtCedula.getText();
            Medico medicoCirujano = controlador.buscarMedicoCirujano(cedulaMedico);
            
            if(medicoCirujano == null){
                JOptionPane.showMessageDialog(null, "No existe un médico con esa cédula");
                return;
            }
            
            String cedulaPaciente = txtCedulaPaciente.getText();
            Paciente paciente = controlador.buscarPaciente(cedulaPaciente);
            
            if(paciente == null){
                JOptionPane.showMessageDialog(null, "No existe un paciente con esa cédula");
            }
            
            LocalTime hora = LocalTime.parse(horaCirugia.getText());
            
            Cirugia cirugia = new Cirugia(paciente, medicoCirujano, motivo, fecha, hora, duracionCirugia, tipo);
            Separado separado = new Separado(cirugia);
            
            controlador.separarQuirofano(separado);
            JOptionPane.showMessageDialog(null, "Quirofano Reservado");
            limpiarCampos();
        }catch(MedicoNoEsCirujanoException | MantenimientoQuirofanoException | AgendaException ex){
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }catch(DateTimeParseException ex){
            JOptionPane.showMessageDialog(null, "Hora invalida");
        }
    }//GEN-LAST:event_btnReservarActionPerformed
     
    private void llenarComboBox(){
        cbxTipoCirugia.setModel(new javax.swing.DefaultComboBoxModel<>(TipoCirugia.obtenerCirugias()));
        cbxTipoCirugia.insertItemAt("Seleccione una opcion", 0);
        cbxTipoCirugia.setSelectedIndex(0);
    }
    
    private boolean camposVacios(){
        return cbxTipoCirugia.getSelectedIndex() == 0 || spnduracionCirugia.getValue().toString().equals(0)
                || txtCedula.getText().isEmpty() || txtCedulaPaciente.getText().isEmpty() || fechaCirugia.getDate() == null
                || txtMotivo.getText().isEmpty() || horaCirugia.getText().isEmpty();
    }
    
    private void limpiarCampos(){
        txtCedula.setText("");
        txtCedulaPaciente.setText("");
        txtMotivo.setText("");
        horaCirugia.setText("");
        fechaCirugia.setDate(null);
        spnduracionCirugia.setValue(0);
        cbxTipoCirugia.setSelectedIndex(0);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReservar;
    private javax.swing.JComboBox<String> cbxTipoCirugia;
    private com.toedter.calendar.JDateChooser fechaCirugia;
    private javax.swing.JFormattedTextField horaCirugia;
    private javax.swing.JLabel lblCedulaPaciente;
    private javax.swing.JLabel lblCedulamedico;
    private javax.swing.JLabel lblDuracion;
    private javax.swing.JLabel lblFechaCirugia;
    private javax.swing.JLabel lblHoraCirugia;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblTipoCirugia;
    private javax.swing.JSpinner spnduracionCirugia;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtCedulaPaciente;
    private javax.swing.JTextField txtMotivo;
    // End of variables declaration//GEN-END:variables
}
