/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import controladores.ControladorMantenimientoQuirofano;
import excepciones.EstaSeparadoException;
import excepciones.MantenimientoQuirofanoException;
import javax.swing.JOptionPane;
import modelos.Mantenimiento;
import modelos.Quirofano;

/**
 *
 * @author LENOVO
 */
public class VentanaMantenimiento extends javax.swing.JInternalFrame {

    private final Quirofano quirofano;
    private final ControladorMantenimientoQuirofano controlador;

    /**
     * Creates new form VentanaMantenimiento
     */
    public VentanaMantenimiento(Quirofano quirofano) {
        initComponents();
        this.quirofano = quirofano;
        controlador = new ControladorMantenimientoQuirofano(quirofano);
        mostrarMotivoMantenimiento();

    }

    private void mostrarMotivoMantenimiento() {

        if (quirofano.getMantenimiento() != null) {
            txtMantenimiento.setText(quirofano.getMantenimiento().getMotivo());
            validar();
        } else {
            validarBoton();
        }

    }

    private void regresar() {
        VentanaGestionesQuirofano ventana = new VentanaGestionesQuirofano(quirofano);
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMantenimiento = new javax.swing.JLabel();
        txtMantenimiento = new javax.swing.JTextField();
        btnGenerar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Mantenimiento");

        lblMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblMantenimiento.setText("Mantenimiento");

        txtMantenimiento.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnGenerar.setText("Generar mantenimiento");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnEliminar.setText("Eliminar mantenimiento");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMantenimiento)
                    .addComponent(txtMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btnGenerar)
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRegresar)
                .addGap(38, 38, 38)
                .addComponent(lblMantenimiento)
                .addGap(38, 38, 38)
                .addComponent(txtMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGenerar)
                    .addComponent(btnEliminar))
                .addGap(39, 39, 39))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        controlador.habilitarQuirofano();
        txtMantenimiento.setText("");
        btnGenerar.setEnabled(true);
        txtMantenimiento.setEditable(true);
        JOptionPane.showMessageDialog(null, "Quirofano habilitado");
        btnEliminar.setEnabled(false);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        String motivo = txtMantenimiento.getText();

        if (motivo.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese el motivo del mantenimiento");
            return;
        }

        Mantenimiento mantenimiento = new Mantenimiento(motivo);

        try {
            controlador.inhabilitarQuirofano(mantenimiento);
            JOptionPane.showMessageDialog(null, "Quirofano deshabilitado");
            validar();
        } catch (MantenimientoQuirofanoException | EstaSeparadoException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            regresar();
        }
    }//GEN-LAST:event_btnGenerarActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        regresar();
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JLabel lblMantenimiento;
    private javax.swing.JTextField txtMantenimiento;
    // End of variables declaration//GEN-END:variables
    public final void validarBoton() {
        btnGenerar.setEnabled(true);
        btnEliminar.setEnabled(false);
    }

    public final void validar() {
        txtMantenimiento.setEnabled(false);
        btnGenerar.setEnabled(false);
        btnEliminar.setEnabled(true);
    }
    
    public final void validarInicio() {
        txtMantenimiento.setEnabled(true);
        btnGenerar.setEnabled(true);
        btnEliminar.setEnabled(true);
    }
}
