/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import controladores.ControladorConsultasMedico;
import java.time.LocalDate;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import modelos.Medico;

/**
 *
 * @author LENOVO
 */
public class VentanaHistorial extends javax.swing.JInternalFrame {
    
    private ControladorConsultasMedico controlador;

    /**
     * Creates new form VentanaHistorial
     */
    public VentanaHistorial() {
        initComponents();
        controlador = new ControladorConsultasMedico();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblFechaInicio = new javax.swing.JLabel();
        lblFechaFinal = new javax.swing.JLabel();
        fechaInicio = new com.toedter.calendar.JDateChooser();
        fechaFinal = new com.toedter.calendar.JDateChooser();
        btnBuscar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        lblNombreMedico = new javax.swing.JLabel();
        lblCedulaMedico = new javax.swing.JLabel();
        lblEspecializacion = new javax.swing.JLabel();
        lblInicioJornada = new javax.swing.JLabel();
        lblFinJornada = new javax.swing.JLabel();
        lblConsulta = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Médicos");

        lblFechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFechaInicio.setText("Fecha inicio");

        lblFechaFinal.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFechaFinal.setText("Fecha final");

        fechaInicio.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        fechaFinal.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnLimpiar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        lblNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblNombreMedico.setText("Nombre médico");

        lblCedulaMedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblCedulaMedico.setText("Cédula médico");

        lblEspecializacion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblEspecializacion.setText("Especialización");

        lblInicioJornada.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblInicioJornada.setText("Hora inicio Jornada");

        lblFinJornada.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFinJornada.setText("Hora fin jornada");

        lblConsulta.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblConsulta.setText("Cantidad consulta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(lblFechaFinal))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(fechaFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addComponent(btnLimpiar))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblConsulta)
                    .addComponent(lblFinJornada)
                    .addComponent(lblInicioJornada)
                    .addComponent(lblEspecializacion)
                    .addComponent(lblCedulaMedico)
                    .addComponent(lblNombreMedico))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFechaInicio)
                    .addComponent(fechaInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFechaFinal)
                            .addComponent(fechaFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnLimpiar)))
                .addGap(96, 96, 96)
                .addComponent(lblNombreMedico)
                .addGap(18, 18, 18)
                .addComponent(lblCedulaMedico)
                .addGap(18, 18, 18)
                .addComponent(lblEspecializacion)
                .addGap(18, 18, 18)
                .addComponent(lblInicioJornada)
                .addGap(18, 18, 18)
                .addComponent(lblFinJornada)
                .addGap(18, 18, 18)
                .addComponent(lblConsulta)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        // TODO add your handling code here:
       if(camposVacios()){
           JOptionPane.showMessageDialog(null, "Ingrese los datos");
           return;
       } 
       
        LocalDate inicio = fechaInicio.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        LocalDate fin = fechaFinal.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        
        if(fin.isBefore(inicio)){
            JOptionPane.showMessageDialog(null, "Seleccione una fecha valida");
            return;
        }
        
        Medico medico = controlador.filtrarMedico(inicio, fin);
        
        if(medico != null){
            mostrarDatos(medico);
        }else{
            JOptionPane.showMessageDialog(null, "No hay consultas para esa fecha");
        }
        
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        fechaInicio.setDate(null);
        fechaFinal.setDate(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    private boolean camposVacios(){
        return fechaInicio.getDate() == null || fechaFinal.getDate() == null;
    }
    
    private void mostrarDatos(Medico medico){
        lblCedulaMedico.setText(medico.getCedula());
        lblNombreMedico.setText(medico.getNombre());
        lblEspecializacion.setText(String.valueOf(medico.getEspecializacion()));
        lblInicioJornada.setText(String.valueOf(medico.getHoraInicioJornada()));
        lblFinJornada.setText(String.valueOf(medico.getHoraFinJornada()));
        lblConsulta.setText(String.valueOf(controlador.getCantidad()));
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnLimpiar;
    private com.toedter.calendar.JDateChooser fechaFinal;
    private com.toedter.calendar.JDateChooser fechaInicio;
    private javax.swing.JLabel lblCedulaMedico;
    private javax.swing.JLabel lblConsulta;
    private javax.swing.JLabel lblEspecializacion;
    private javax.swing.JLabel lblFechaFinal;
    private javax.swing.JLabel lblFechaInicio;
    private javax.swing.JLabel lblFinJornada;
    private javax.swing.JLabel lblInicioJornada;
    private javax.swing.JLabel lblNombreMedico;
    // End of variables declaration//GEN-END:variables
}
