/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import modelos.Atencion;
import modelos.PQRS;

/**
 *
 * @author LENOVO
 */
public class VentanaDetallesPQRS extends javax.swing.JInternalFrame {
    private PQRS pqrs;
    

    /**
     * Creates new form VenatanDetallesPQRS
     */
    public VentanaDetallesPQRS(PQRS pqrs) {
        initComponents();
        this.pqrs = pqrs;
        mostrarDetalles();
        
    }
    
    private void mostrarDetalles(){
        Atencion atencion = (Atencion) pqrs.getAtencion();
        lblNombreMedico.setText(atencion.getCita().getMedico().getNombre());
        lblCedulaMedico.setText(atencion.getCita().getMedico().getCedula());
        lblHora.setText(String.valueOf(atencion.getCita().getHoraInicio()));
        lblFecha.setText(String.valueOf(atencion.getCita().getFecha()));
        lblMotivo.setText(atencion.getCita().getMotivo());
        lblTratamiento.setText(atencion.getTratamiento());
        txtNotas.setText(atencion.getNota());
        
        txtNotas.setEditable(false);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreMedico = new javax.swing.JLabel();
        lblCedulaMedico = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        lblTratamiento = new javax.swing.JLabel();
        lblNotas = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtNotas = new javax.swing.JTextArea();
        btnRegresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Detalles PQRS");

        lblNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblNombreMedico.setText("Nombre médico");

        lblCedulaMedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblCedulaMedico.setText("Cédula médico");

        lblHora.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblHora.setText("Hora");

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFecha.setText("Fecha");

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblMotivo.setText("Motivo");

        lblTratamiento.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblTratamiento.setText("Tratamiento");

        lblNotas.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblNotas.setText("Notas");

        txtNotas.setColumns(20);
        txtNotas.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        txtNotas.setRows(5);
        jScrollPane1.setViewportView(txtNotas);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(143, 143, 143)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNotas)
                    .addComponent(lblTratamiento)
                    .addComponent(lblMotivo)
                    .addComponent(lblFecha)
                    .addComponent(lblHora)
                    .addComponent(lblCedulaMedico)
                    .addComponent(lblNombreMedico))
                .addContainerGap(259, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(82, 82, 82))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addComponent(lblNombreMedico)
                .addGap(26, 26, 26)
                .addComponent(lblCedulaMedico)
                .addGap(18, 18, 18)
                .addComponent(lblHora)
                .addGap(18, 18, 18)
                .addComponent(lblFecha)
                .addGap(18, 18, 18)
                .addComponent(lblMotivo)
                .addGap(18, 18, 18)
                .addComponent(lblTratamiento)
                .addGap(18, 18, 18)
                .addComponent(lblNotas)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addComponent(btnRegresar)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaAtencionPQRS ventana = new VentanaAtencionPQRS();
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCedulaMedico;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblNotas;
    private javax.swing.JLabel lblTratamiento;
    private javax.swing.JTextArea txtNotas;
    // End of variables declaration//GEN-END:variables
}
