/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Cirugia;
import modelos.Quirofano;
import modelos.Separado;
import util.LSE;

/**
 *
 * @author LENOVO
 */
public class VentanaReservas extends javax.swing.JInternalFrame {
    
    private Quirofano quirofano;
    

    /**
     * Creates new form VentanaReservas
     */
    public VentanaReservas(Quirofano quirofano) {
        initComponents();
        this.quirofano = quirofano;
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaQuirofanos = new javax.swing.JTable();
        btnRegresar = new javax.swing.JButton();
        btnGestiones = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ver reservas");

        tablaQuirofanos.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        tablaQuirofanos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaQuirofanos);

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        btnGestiones.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnGestiones.setText("Gestiones adicionales");
        btnGestiones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(199, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(btnRegresar)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGap(303, 303, 303)
                .addComponent(btnGestiones)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(btnRegresar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)))
                .addComponent(btnGestiones)
                .addGap(60, 60, 60))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaGestionesQuirofano ventana = new VentanaGestionesQuirofano(quirofano);
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnGestionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionesActionPerformed
        // TODO add your handling code here:
        int selec = tablaQuirofanos.getSelectedRow();
        
        if(selec >=0){
            int id = (int) tablaQuirofanos.getModel().getValueAt(selec, 0);
            Separado separado = quirofano.buscarQuirofanoSeparado(id);
            Cirugia cirugia = separado.getCirugia();
            
            VentanaGestionReserva ventana = new VentanaGestionReserva(cirugia);
            VentanaOpcionesAdmin.background.add(ventana);
            ventana.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una cirugía");
        }
    }//GEN-LAST:event_btnGestionesActionPerformed
    
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        LSE<Separado> separados = quirofano.getSeparados();
        modelo.setColumnIdentifiers(new Object[]{
            "ID","Fecha", "Horas"
        });
        
        tablaQuirofanos.setModel(modelo);
        
        for(int i = 0; i < separados.size(); i++){
            Separado separado = separados.get(i);
            modelo.addRow(new Object[]{
                separado.getId(),
                separado.getFecha(),
                separado.getHoraInicio() + "/" + separado.getHoraFinal()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGestiones;
    private javax.swing.JButton btnRegresar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaQuirofanos;
    // End of variables declaration//GEN-END:variables
}
