/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import enums.Rol;
import javax.swing.table.DefaultTableModel;
import modelos.Enfermera;
import modelos.Instrumental;
import modelos.Medico;
import modelos.Persona;
import modelos.Quirofano;
import modelos.Separado;
import util.LSE;
import vistas.paciente.VentanaHistorial;

/**
 *
 * @author LENOVO
 */
public class VentanaInformacionCirugia extends javax.swing.JInternalFrame {
    private Separado separado;
    private Quirofano quirofano;

    /**
     * Creates new form VentanaInformacionCirugia
     */
    public VentanaInformacionCirugia(Separado separado, Quirofano quirofano) {
        initComponents();
        this.separado = separado;
        this.quirofano = quirofano;
        mostrarInformacion();
        llenarTablaMedicosAsignados();
        llenarTablaEnfermerasAsignadas();
        llenarTablaInstrumentos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaInstrumental = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEnfermerasAsignadas = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaMedicosAsignados = new javax.swing.JTable();
        lblNombre = new javax.swing.JLabel();
        lblNombreMedico = new javax.swing.JLabel();
        lblMotivo = new javax.swing.JLabel();
        lblNombrePaciente = new javax.swing.JLabel();
        lblNombreM = new javax.swing.JLabel();
        lblMotivo2 = new javax.swing.JLabel();
        btnVerHistorial = new javax.swing.JButton();
        btnSeparar = new javax.swing.JButton();
        btnVerReservas = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("VentanaInformacion");

        tablaInstrumental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaInstrumental);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Instrumental", jPanel2);

        tablaEnfermerasAsignadas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaEnfermerasAsignadas);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(131, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Enfermeras", jPanel1);

        tablaMedicosAsignados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaMedicosAsignados);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 569, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(134, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Médicos", jPanel3);

        lblNombre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblNombre.setText("Nombre");

        lblNombreMedico.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblNombreMedico.setText("Médico ");

        lblMotivo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblMotivo.setText("Motivo");

        lblNombrePaciente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        lblNombreM.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        lblMotivo2.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        btnVerHistorial.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnVerHistorial.setText("Ver historial");
        btnVerHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerHistorialActionPerformed(evt);
            }
        });

        btnSeparar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnSeparar.setText("Separar quirofano");
        btnSeparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSepararActionPerformed(evt);
            }
        });

        btnVerReservas.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnVerReservas.setText("Ver reservas");
        btnVerReservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerReservasActionPerformed(evt);
            }
        });

        btnRegresar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(0, 0, 153));
        btnRegresar.setText("Regresar");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombre)
                            .addComponent(lblNombreMedico)
                            .addComponent(lblMotivo))
                        .addGap(66, 66, 66)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNombrePaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                            .addComponent(lblNombreM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblMotivo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVerReservas)
                                .addGap(142, 142, 142))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnSeparar)
                                        .addGap(121, 121, 121))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnVerHistorial)
                                        .addGap(151, 151, 151))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnRegresar)
                                        .addGap(166, 166, 166))))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNombre)
                            .addComponent(lblNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegresar)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreM, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblMotivo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNombreMedico)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMotivo)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnVerHistorial)
                                .addGap(189, 189, 189))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSeparar)
                                .addGap(32, 32, 32)
                                .addComponent(btnVerReservas)
                                .addGap(54, 54, 54)))))
                .addComponent(tabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVerHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerHistorialActionPerformed
        // TODO add your handling code here:
        VentanaHistorial ventana = new VentanaHistorial(separado.getCirugia().getPaciente());
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVerHistorialActionPerformed

    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // TODO add your handling code here:
        VentanaBotones ventana = new VentanaBotones();
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnSepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSepararActionPerformed
        // TODO add your handling code here:
        VentanaQuirofano ventana = new VentanaQuirofano(quirofano);
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_btnSepararActionPerformed

    private void btnVerReservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerReservasActionPerformed
        // TODO add your handling code here:
        VentanaReservas ventana = new VentanaReservas(quirofano);
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVerReservasActionPerformed
    
    private void mostrarInformacion(){
        lblNombrePaciente.setText(separado.getCirugia().getPaciente().getNombre());
        lblNombreM.setText(separado.getCirugia().getCirujano().getNombre());
        lblMotivo2.setText(separado.getCirugia().getMotivo());
    }
    
    private void llenarTablaMedicosAsignados(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        LSE<Persona> personalSalud = separado.getCirugia().getPersonalSalud();
        modelo.setColumnIdentifiers(new Object[]{
            "Cédula", "Nombre", "Especialización"
        });
        
        tablaMedicosAsignados.setModel(modelo);
        for(int i = 0; i < personalSalud.size(); i++){
            Persona persona = personalSalud.get(i);
            if(persona.getRol() == Rol.MEDICO){
                Medico medico = (Medico) persona;
                modelo.addRow(new Object[]{
                    medico.getCedula(),
                    medico.getNombre(),
                    medico.getEspecializacion()
                });
            }
        }
    }
    
    private void llenarTablaEnfermerasAsignadas(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        LSE<Persona> personalSalud = separado.getCirugia().getPersonalSalud();
        modelo.setColumnIdentifiers(new Object[]{
            "Cédula", "Nombre"
        });
        tablaEnfermerasAsignadas.setModel(modelo);
        for(int i = 0; i < personalSalud.size(); i++){
            Persona persona = personalSalud.get(i);
            if(persona.getRol() == Rol.ENFERMERA){
                Enfermera enfermera = (Enfermera) persona;
                modelo.addRow(new Object[]{
                    enfermera.getCedula(),
                    enfermera.getNombre()
                });
            }
        }
    }
    
    private void llenarTablaInstrumentos(){
         DefaultTableModel modelo = new DefaultTableModel();
        LSE<Instrumental> instrumentos = separado.getCirugia().getInstrumental();
        modelo.setColumnIdentifiers(new Object[]{
            "Nombre instrumento", "Cantidad"
        });
        tablaInstrumental.setModel(modelo);
        for(int i = 0; i < instrumentos.size(); i++){
            Instrumental instrumental = instrumentos.get(i);
            modelo.addRow(new Object[]{
                instrumental.getNombreInstrumento(),
                instrumental.getCantidad()
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegresar;
    private javax.swing.JButton btnSeparar;
    private javax.swing.JButton btnVerHistorial;
    private javax.swing.JButton btnVerReservas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblMotivo2;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombreM;
    private javax.swing.JLabel lblNombreMedico;
    private javax.swing.JLabel lblNombrePaciente;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable tablaEnfermerasAsignadas;
    private javax.swing.JTable tablaInstrumental;
    private javax.swing.JTable tablaMedicosAsignados;
    // End of variables declaration//GEN-END:variables
}
