/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.admin;

import controladores.ControladorPQRSAdmin;
import excepciones.NoHayPQRSException;
import excepciones.PQRSEnAtencionException;
import javax.swing.JOptionPane;
import modelos.PQRS;
import modelos.Paciente;


/**
 *
 * @author LENOVO
 */
public class VentanaAtencionPQRS extends javax.swing.JInternalFrame {

    private PQRS pqrsAtencion;
    private ControladorPQRSAdmin controlador;

    /**
     * Creates new form VentanaAtencionPQRS
     */
    public VentanaAtencionPQRS() {
        initComponents();
        controlador = new ControladorPQRSAdmin();
        mostrarSiguiente();
        mostrarPQRSAtencion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAtencion = new javax.swing.JLabel();
        lblVerAtencion = new javax.swing.JLabel();
        lblFecha = new javax.swing.JLabel();
        lblFechaAtencion = new javax.swing.JLabel();
        btnPasar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtMotivo = new javax.swing.JTextArea();
        btnVerMas = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        lblRespuesta = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtRespuesta = new javax.swing.JTextArea();
        btnGenerarAtencion = new javax.swing.JButton();
        lblPaciente = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Atención PQRS");

        lblAtencion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblAtencion.setText("Por atender");

        lblVerAtencion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        lblFecha.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblFecha.setText("Fecha");

        lblFechaAtencion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        btnPasar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnPasar.setText("Pasar");
        btnPasar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPasarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        jLabel1.setText("Atención");

        txtMotivo.setColumns(20);
        txtMotivo.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        txtMotivo.setRows(5);
        jScrollPane1.setViewportView(txtMotivo);

        btnVerMas.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnVerMas.setText("Ver más");
        btnVerMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerMasActionPerformed(evt);
            }
        });

        lblRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        lblRespuesta.setText("Respuesta");

        txtRespuesta.setColumns(20);
        txtRespuesta.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        txtRespuesta.setRows(5);
        jScrollPane2.setViewportView(txtRespuesta);

        btnGenerarAtencion.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnGenerarAtencion.setText("Generar Atención");
        btnGenerarAtencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarAtencionActionPerformed(evt);
            }
        });

        lblPaciente.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnPasar)
                .addGap(331, 331, 331))
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAtencion)
                            .addComponent(lblFecha))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblVerAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblFechaAtencion, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(185, 185, 185)
                                .addComponent(btnVerMas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(163, 163, 163)
                                .addComponent(btnGenerarAtencion))
                            .addComponent(lblRespuesta))))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAtencion)
                    .addComponent(lblVerAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPasar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblFecha)
                    .addComponent(lblFechaAtencion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(btnVerMas)))
                .addGap(62, 62, 62)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addComponent(lblRespuesta)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGenerarAtencion)
                        .addGap(106, 106, 106))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGenerarAtencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarAtencionActionPerformed
        // TODO add your handling code here:
        if (pqrsAtencion == null) {
            JOptionPane.showMessageDialog(null, "No hay PQRS por atender");
            return;
        }
        String resp = txtRespuesta.getText();

        if (resp.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Ingrese una respuesta a la PQRS");
            return;
        }

        pqrsAtencion.setRespuesta(resp);
        controlador.atenderPQRS(pqrsAtencion);

        JOptionPane.showMessageDialog(null, "PQRS atendida");

        pqrsAtencion = null;
        limpiarCampos();
    }//GEN-LAST:event_btnGenerarAtencionActionPerformed

    private void btnPasarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPasarActionPerformed
        // TODO add your handling code here:
        try {
            if (pqrsAtencion != null) {
                throw new PQRSEnAtencionException();
            } else {
                PQRS peticion = controlador.saltarPQRS();
                Paciente paciente = peticion.getPaciente();

                lblPaciente.setText(paciente.getNombre());
                txtMotivo.setText(peticion.getMotivo());
                controlador.pasarEnProceso(peticion);
                pqrsAtencion = peticion;
                mostrarSiguiente();
            }
        } catch (NoHayPQRSException | PQRSEnAtencionException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnPasarActionPerformed

    private void btnVerMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerMasActionPerformed
        // TODO add your handling code here:
        VentanaDetallesPQRS ventana = new VentanaDetallesPQRS(pqrsAtencion);
        VentanaOpcionesAdmin.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_btnVerMasActionPerformed

    private void mostrarSiguiente() {
        try {
            PQRS pqrsSiguiente = controlador.mostrarSiguiente();
            Paciente paciente = pqrsSiguiente.getPaciente();
            lblVerAtencion.setText(paciente.getNombre());
            lblFechaAtencion.setText(pqrsSiguiente.getFecha().toString());
        } catch (NoHayPQRSException ex) {
            lblAtencion.setText(ex.getMessage());
            lblFechaAtencion.setText("");

        }
    }

    private void mostrarPQRSAtencion() {
        PQRS pqrs = controlador.mostrarPQRS();
        pqrsAtencion = pqrs;

        if (pqrs != null) {

            Paciente paciente = pqrs.getPaciente();
            lblPaciente.setText(paciente.getNombre());
            txtMotivo.setText(pqrs.getMotivo());
        } else {
            lblPaciente.setText("");
            txtMotivo.setText("");
        }

    }

    private void limpiarCampos() {
        lblPaciente.setText("");
        txtMotivo.setText("");
        txtRespuesta.setText("");
        lblVerAtencion.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerarAtencion;
    private javax.swing.JButton btnPasar;
    private javax.swing.JButton btnVerMas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblAtencion;
    private javax.swing.JLabel lblFecha;
    private javax.swing.JLabel lblFechaAtencion;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblRespuesta;
    private javax.swing.JLabel lblVerAtencion;
    private javax.swing.JTextArea txtMotivo;
    private javax.swing.JTextArea txtRespuesta;
    // End of variables declaration//GEN-END:variables
}
