/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.paciente;

import controladores.ControladorHistorialPaciente;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelos.Atencion;
import modelos.Paciente;
import util.LSE;


/**
 *
 * @author LENOVO
 */
public class VentanaHistorial extends javax.swing.JInternalFrame {
    ControladorHistorialPaciente controlador;
    private Paciente paciente;
    /**
     * Creates new form VentanaHistorial
     */
    public VentanaHistorial(Paciente paciente) {
        initComponents();
        this.paciente = paciente;
        controlador = new ControladorHistorialPaciente(paciente);
        llenarTabla();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnDetalles = new javax.swing.JButton();
        btnGenerar = new javax.swing.JButton();
        cirugias = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaHistorial = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Historial");

        btnDetalles.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnDetalles.setText("Ver detalles");
        btnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDetallesActionPerformed(evt);
            }
        });

        btnGenerar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnGenerar.setText("Generar PQRS");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        cirugias.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        tablaHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaHistorial);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(116, Short.MAX_VALUE))
        );

        cirugias.addTab("Citas", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cirugias)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnGenerar)
                    .addComponent(btnDetalles, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cirugias, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnDetalles)
                        .addGap(54, 54, 54)
                        .addComponent(btnGenerar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDetallesActionPerformed
        
        int seleccionado = tablaHistorial.getSelectedRow();

        if (seleccionado >= 0) {
            int id = (int) tablaHistorial.getModel().getValueAt(seleccionado, 0);
            Atencion atencion = controlador.buscarAtencion(id);

            VentanaDetalles ventana = new VentanaDetalles(atencion);
            VentanaOpcionesPaciente.background.add(ventana);
            ventana.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(null, "Seleccione una cita");
        }
    }//GEN-LAST:event_btnDetallesActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        int seleccion = tablaHistorial.getSelectedRow();
        
        if(seleccion >= 0){
            int id = (int) tablaHistorial.getModel().getValueAt(seleccion, 0);
            Atencion atencion = controlador.buscarAtencion(id);
            
            VentanaGenerarPQRS ventana = new VentanaGenerarPQRS(paciente, atencion);
            VentanaOpcionesPaciente.background.add(ventana);
            ventana.setVisible(true);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Seleccione una cita");
        }
    }//GEN-LAST:event_btnGenerarActionPerformed
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        LSE<Atencion> atenciones = controlador.getAtenciones();
        
        modelo.setColumnIdentifiers(new Object[]{
           "ID", "Médico", "Fecha", "Hora"
        });
        
        tablaHistorial.setModel(modelo);
        
        for(int i = 0; i < atenciones.size(); i++){
            modelo.addRow(new Object[]{
                atenciones.get(i).getId(),
                atenciones.get(i).getCita().getMedico().getNombre(),
                atenciones.get(i).getCita().getFecha(),
                atenciones.get(i).getCita().getHoraFinal()
                
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalles;
    private javax.swing.JButton btnGenerar;
    private javax.swing.JTabbedPane cirugias;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaHistorial;
    // End of variables declaration//GEN-END:variables
}
