/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.medico;

import javax.swing.table.DefaultTableModel;
import modelos.Atencion;
import modelos.Medico;
import util.LSE;

/**
 *
 * @author LENOVO
 */
public class VentanaHistorialAtenciones extends javax.swing.JInternalFrame {
    
    private Medico medico;

    /**
     * Creates new form VentanaHistorialAtenciones
     */
    public VentanaHistorialAtenciones(Medico medico) {
        initComponents();
        this.medico = medico;
        llenarTabla();
    }
    
    private void llenarTabla(){
        DefaultTableModel modelo = new DefaultTableModel();
        
        LSE<Atencion> atenciones = medico.getHistorialConsultas();
        
        modelo.setColumnIdentifiers(new Object[]{
            "Cédula paciente", "Nombre", "Fecha", "Diagnostico"
        });
        
        tablaAtenciones.setModel(modelo);
        
        for(int i = 0; i < atenciones.size(); i++){
            modelo.addRow(new Object[]{
                atenciones.get(i).getCita().getPaciente().getCedula(),
                atenciones.get(i).getCita().getPaciente().getNombre(),
                atenciones.get(i).getCita().getFecha(),
                atenciones.get(i).getDiagnostico()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaAtenciones = new javax.swing.JTable();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Historial atenciones");

        tablaAtenciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaAtenciones);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(130, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(73, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaAtenciones;
    // End of variables declaration//GEN-END:variables
}
