/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas.medico;

import controladores.ControladorDiaLibre;
import excepciones.AgendaException;
import excepciones.DiaLibreInvalidoException;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import javax.swing.JOptionPane;
import modelos.Medico;

/**
 *
 * @author LENOVO
 */
public class VentanaDiaLibre extends javax.swing.JInternalFrame {

    private Medico medico;
    private ControladorDiaLibre controlador;

    /**
     * Creates new form VentanaDiaLibre
     */
    public VentanaDiaLibre(Medico medico) {
        initComponents();
        this.medico = medico;
        controlador = new ControladorDiaLibre(medico);
        mostrarDiaLibre();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaLibre = new com.toedter.calendar.JDateChooser();
        btnDiaLibre = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        lblDiaLibre = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Programar día libre");

        btnDiaLibre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnDiaLibre.setText("Programar día");
        btnDiaLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiaLibreActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        lblDiaLibre.setFont(new java.awt.Font("Segoe UI", 0, 19)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(btnDiaLibre))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(diaLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDiaLibre, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar))
                .addGap(95, 95, 95))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(94, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(diaLibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDiaLibre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDiaLibre)
                    .addComponent(btnEliminar))
                .addGap(92, 92, 92))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDiaLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiaLibreActionPerformed
        // TODO add your handling code here:
        Date date = diaLibre.getDate();

        if (date == null) {
            JOptionPane.showMessageDialog(null, "ingrese una fecha");
            return;
        }
        LocalDate fecha = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();

        try {
            boolean respuesta = controlador.programarDialibre(fecha);
            if (respuesta) {
                JOptionPane.showMessageDialog(null, "Día libre programado");
                lblDiaLibre.setText(String.valueOf(fecha));
                diaLibre.setDate(null);
            }else{
                JOptionPane.showMessageDialog(null, "Ya tiene un día libre programado");
                        
            }

        } catch (DiaLibreInvalidoException | AgendaException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnDiaLibreActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:
        if(lblDiaLibre.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "No hay un día libre programado");
            return;
        }
        controlador.eliminarDiaLibre();
        JOptionPane.showMessageDialog(null, "Día libre eliminado");
        lblDiaLibre.setText("");
    }//GEN-LAST:event_btnEliminarActionPerformed
    
    private void mostrarDiaLibre(){
        if(medico.tieneDiaLibre()){
            lblDiaLibre.setText(String.valueOf(medico.getDiaLibre()));
        }else{
            lblDiaLibre.setText("Sin programar");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDiaLibre;
    private javax.swing.JButton btnEliminar;
    private com.toedter.calendar.JDateChooser diaLibre;
    private javax.swing.JLabel lblDiaLibre;
    // End of variables declaration//GEN-END:variables
}
