/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistas.medico;

import modelos.Medico;
import vista.login.VentanaLogin;

/**
 *
 * @author LENOVO
 */
public class VentanaOpcionesMedico extends javax.swing.JFrame {
    private Medico medico;

    /**
     * Creates new form VentanaOpcionesMedico
     */
    public VentanaOpcionesMedico(Medico medico) {
        initComponents();
        setLocationRelativeTo(this);
        this.medico = medico;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        atencion = new javax.swing.JMenuItem();
        programarDia = new javax.swing.JMenuItem();
        historial = new javax.swing.JMenuItem();
        salir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout backgroundLayout = new javax.swing.GroupLayout(background);
        background.setLayout(backgroundLayout);
        backgroundLayout.setHorizontalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 539, Short.MAX_VALUE)
        );
        backgroundLayout.setVerticalGroup(
            backgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 403, Short.MAX_VALUE)
        );

        jMenu1.setText("Opciones");

        atencion.setText("Ver citas programadas");
        atencion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atencionActionPerformed(evt);
            }
        });
        jMenu1.add(atencion);

        programarDia.setText("Programar día libre");
        programarDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                programarDiaActionPerformed(evt);
            }
        });
        jMenu1.add(programarDia);

        historial.setText("Historial");
        historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialActionPerformed(evt);
            }
        });
        jMenu1.add(historial);

        jMenuBar1.add(jMenu1);

        salir.setText("Salir");
        salir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                salirMouseClicked(evt);
            }
        });
        jMenuBar1.add(salir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salirMouseClicked
        // TODO add your handling code here:
        VentanaLogin ventana = new VentanaLogin();
        ventana.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_salirMouseClicked

    private void programarDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_programarDiaActionPerformed
        // TODO add your handling code here:
        VentanaDiaLibre ventana = new VentanaDiaLibre(medico);
        VentanaOpcionesMedico.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_programarDiaActionPerformed

    private void atencionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atencionActionPerformed
        // TODO add your handling code here:
        VentanaVerCitas ventana = new VentanaVerCitas(medico);
        VentanaOpcionesMedico.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_atencionActionPerformed

    private void historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialActionPerformed
        // TODO add your handling code here:
        VentanaHistorialAtenciones ventana = new VentanaHistorialAtenciones(medico);
        VentanaOpcionesMedico.background.add(ventana);
        ventana.setVisible(true);
    }//GEN-LAST:event_historialActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem atencion;
    public static javax.swing.JDesktopPane background;
    private javax.swing.JMenuItem historial;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem programarDia;
    private javax.swing.JMenu salir;
    // End of variables declaration//GEN-END:variables
}
